FROM sugupta/wso2is-km:5.3.0

COPY conf/ /home/wso2carbon/wso2is-km-5.3.0/repository/conf/
COPY components/ /home/wso2carbon/wso2is-km-5.3.0/repository/components/
COPY wso2start.sh /home/wso2carbon/wso2is-km-5.3.0/bin/
COPY wso2server.sh /home/wso2carbon/wso2is-km-5.3.0/bin/
COPY resources/ /home/wso2carbon/wso2is-km-5.3.0/repository/resources/