From sugupta/wso2am-analytics:2.1.0

COPY conf/ /home/wso2carbon/wso2am-analytics-2.1.0/repository/conf/
COPY wso2start.sh /home/wso2carbon/wso2am-analytics-2.1.0/bin/
COPY resources/ /home/wso2carbon/wso2am-analytics-2.1.0/repository/resources/
